# Generated by Django 5.2.6 on 2025-10-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/common/default.jpg', upload_to='profile_pics'),
        ),
    ]
