# Generated by Django 5.2.6 on 2025-10-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='common/default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
