# Generated by Django 5.2.6 on 2025-10-15 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_commentreaction_commentreport_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
